use_frameworks!

platform :ios, '8.0'

pod 'mob_sharesdk'
pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
#（微信sdk不带支付的命令）
pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
#（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个
# pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'）

target 'YDShareSDK_Example' do
  pod 'YDShareSDK', :path => '../'

  target 'YDShareSDK_Tests' do
    inherit! :search_paths

    
  end
  end
  pre_install do |installer| Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
